// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqirktngsdbzvluenvgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxaXJrdG5nc2RienZsdWVudmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjM3NTYsImV4cCI6MjA2MzUzOTc1Nn0.dwyHHQoSGlxQR9T7Wmrb4EZmn8fZxJ6FBUUFkqadwZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);